[workspace]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
name = "5_orthofinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
orthofinder = { version = ">=3.1.4,<4", channel = "bioconda" }
